# Generated by Django 4.2.23 on 2025-08-19 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0002_projects"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterFaces",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="自增主键id",
                        primary_key=True,
                        serialize=False,
                        verbose_name="主键",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="接口名称")),
                (
                    "create_time",
                    models.TimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.TimeField(auto_now=True, verbose_name="修改时间"),
                ),
                (
                    "projects",
                    models.ForeignKey(
                        help_text="外键id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.projects",
                        verbose_name="所属项目id",
                    ),
                ),
            ],
            options={
                "verbose_name": "接口表",
                "verbose_name_plural": "接口表",
                "db_table": "tb_interfaces",
                "ordering": ["id"],
            },
        ),
    ]
