# Generated by Django 4.2.23 on 2025-08-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="projects",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        help_text="项目id为主键",
                        primary_key=True,
                        serialize=False,
                        verbose_name="主键",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="项目名称",
                        max_length=50,
                        unique=True,
                        verbose_name="项目名称",
                    ),
                ),
                (
                    "leader",
                    models.CharField(
                        help_text="项目负责人",
                        max_length=50,
                        null=True,
                        verbose_name="项目负责人",
                    ),
                ),
                (
                    "is_execute",
                    models.BooleanField(
                        default=True,
                        help_text="1:启动 2:暂停",
                        verbose_name="是否启动项目",
                    ),
                ),
                (
                    "desc",
                    models.TextField(
                        blank=True,
                        help_text="请输入项目描述",
                        null=True,
                        verbose_name="项目描述",
                    ),
                ),
                (
                    "create_time",
                    models.TimeField(auto_now_add=True, verbose_name="项目创建时间"),
                ),
                (
                    "update_time",
                    models.TimeField(auto_now=True, verbose_name="修改时间"),
                ),
            ],
            options={
                "verbose_name": "项目表",
                "db_table": "tb_project",
                "ordering": ["id"],
            },
        ),
    ]
