# Generated by Django 4.2.23 on 2025-08-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_projects_create_time_alter_projects_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projects",
            name="create_time",
            field=models.TimeField(auto_now_add=True, verbose_name="项目创建时间"),
        ),
        migrations.AlterField(
            model_name="projects",
            name="id",
            field=models.AutoField(
                help_text="项目id为主键",
                primary_key=True,
                serialize=False,
                verbose_name="主键",
            ),
        ),
    ]
